apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongodb
  labels:
    {{- include "librechat.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "librechat.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mongodb
  template:
    metadata:
      labels:
        {{- include "librechat.labels" . | nindent 8 }}
        app.kubernetes.io/component: mongodb
    spec:
      containers:
          - name: mongodb
            image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
            args: ["--noauth"]
            ports:
              - containerPort: 27017
            volumeMounts:
              - name: data
                mountPath: /data/db
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 512Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-mongodb


