apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb
  labels:
    {{- include "librechat.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    {{- include "librechat.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
