apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rag
  labels:
    {{- include "librechat.labels" . | nindent 4 }}
    app.kubernetes.io/component: rag
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    {{- include "librechat.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: rag
