apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-vectordb
  labels:
    {{- include "librechat.labels" . | nindent 4 }}
    app.kubernetes.io/component: vectordb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.vectordb.persistence.size }}
