apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-vectordb
  labels:
    {{- include "librechat.labels" . | nindent 4 }}
    app.kubernetes.io/component: vectordb
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    {{- include "librechat.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: vectordb
