apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "librechat.labels" . | nindent 4 }}
spec:
  entryPoints:
    - "websecure"
  routes:
    - kind: "Rule"
      match: {{ .Values.traefik.match }}
      services:
        - name: {{ .Release.Name }}-api
          port: 3080
