apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongodb
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
type: Opaque
data:
  root-username: {{ "root" | b64enc }}
  root-password: {{ lookup "v1" "Secret" .Release.Namespace (printf "%s-mongodb" .Release.Name) | dig "data" "root-password" (randAlphaNum 50 | b64enc) }}

