apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: mongodb
      port: {{ .Values.service.ports.mongodb }}
      targetPort: mongodb
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePorts.mongodb }}
      nodePort: {{ .Values.service.nodePorts.mongodb }}
      {{- end }}
  selector:
    {{- include "mongodb.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
