apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-meilisearch
  labels:
    {{- include "librechat.labels" . | nindent 4 }}
    app.kubernetes.io/component: meilisearch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.meilisearch.persistence.size }}
