apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-meilisearch
  labels:
    {{- include "librechat.labels" . | nindent 4 }}
    app.kubernetes.io/component: meilisearch
spec:
  type: ClusterIP
  ports:
    - port: 7700
      targetPort: 7700
  selector:
    {{- include "librechat.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: meilisearch
