apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-librechat
  labels:
    {{- include "librechat.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
data:
  librechat.yaml: |
    version: 1.2.0
    cache: true

    # See https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/registration
    registration:
      allowedDomains:
        {{- toYaml .Values.registrationDomains | nindent 8 }}

    endpoints:
      custom:
        {{- toYaml .Values.endpoints | nindent 8 }}
