apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
  annotations:
    {{- include "prometheus.annotations" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 30s
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets: [localhost:9090]
