apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
  annotations:
    {{- include "prometheus.annotations" . | nindent 4 }}
spec:
  selector:
    {{- include "prometheus.labels" . | nindent 4 }}
  ports:
    - name: http
      port: 9090
      targetPort: 9090
